# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

In [131]:
'''
1. 在一維情況下，兩者沒有區別
2. 在二維情況下，list(a) 只會把第一層的元素轉換為 List; tolist() 則可以將多層的 array 都轉換為 List
'''

'\n1. 在一維情況下，兩者沒有區別\n2. 在二維情況下，list(a) 只會把第一層的元素轉換為 List; tolist() 則可以將多層的 array 都轉換為 List\n'

import numpy as np

a = np.random.randint(10, size = 6)
print("list(a): ", list(a))
print("tolist(): ", a.tolist())

b = np.random.randint(10, size = 6).reshape(2, 3)
print("list(b): ", list(b))
print("tolist(): ", b.tolist())

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [132]:
import numpy as np

a = np.random.randint(10, size=6) 

print(a)
print("陣列維度: ", a.ndim)
print("每一維度的數量: ", a.shape)
print("總元素數量: ", a.size)
print("陣列中的元素型態:", a.dtype)
print("每一元素所佔空間[byte]: ", a.itemsize)
print("陣列所在位址: ", a.data)

[6 1 7 2 1 4]
陣列維度:  1
每一維度的數量:  (6,)
總元素數量:  6
陣列中的元素型態: int64
每一元素所佔空間[byte]:  8
陣列所在位址:  <memory at 0x115034d00>


In [133]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print("陣列維度: ", b.ndim)
print("每一維度的數量: ", b.shape)
print("總元素數量: ", b.size)
print("陣列中的元素型態:", b.dtype)
print("每一元素所佔空間[byte]: ", b.itemsize)
print("陣列所在位址: ", b.data)

[[5 9 5 1]
 [8 2 3 7]
 [3 5 5 6]]
陣列維度:  2
每一維度的數量:  (3, 4)
總元素數量:  12
陣列中的元素型態: int64
每一元素所佔空間[byte]:  8
陣列所在位址:  <memory at 0x110882c70>


In [134]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print("陣列維度: ", c.ndim)
print("每一維度的數量: ", c.shape)
print("總元素數量: ", c.size)
print("陣列中的元素型態:", c.dtype)
print("每一元素所佔空間[byte]: ", c.itemsize)
print("陣列所在位址: ", c.data)

[[[7 6]
  [5 9]
  [5 0]]

 [[1 1]
  [2 3]
  [2 0]]]
陣列維度:  3
每一維度的數量:  (2, 3, 2)
總元素數量:  12
陣列中的元素型態: int64
每一元素所佔空間[byte]:  8
陣列所在位址:  <memory at 0x115032220>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [138]:
def tolist(data):
    if type(data) != np.ndarray:
        return data
    return [tolist(item) for item in data]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 1, 7, 2, 1, 4]
[[5, 9, 5, 1], [8, 2, 3, 7], [3, 5, 5, 6]]
[[[7, 6], [5, 9], [5, 0]], [[1, 1], [2, 3], [2, 0]]]


In [157]:
def tolist(data):
    if type(data) != np.ndarray:
        return data
    newlist = []
    for item in data:
        newlist.append(tolist(item))
    return tolist(newlist)
   
print(tolist(a))
print(tolist(b))
print(tolist(c))   

[6, 1, 7, 2, 1, 4]
[[5, 9, 5, 1], [8, 2, 3, 7], [3, 5, 5, 6]]
[[[7, 6], [5, 9], [5, 0]], [[1, 1], [2, 3], [2, 0]]]
