In [5]:
import numpy as np

print(np)
print(np.__version__)

<module 'numpy' from '/Users/susan_yan/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.20.1


In [6]:
# 從一個陣列開始

a = np.arange(15).reshape(3, 5)
print(a) # 利用 print 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
# 陣列的常用屬性
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

<class 'numpy.ndarray'>
2
(3, 5)
15
int64
8


In [11]:
# numpy.array 轉換成 python list
print(list(a))
print(a.tolist())

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
