# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

In [7]:
import numpy as np

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？
a = np.array( [20, 30, 40, 50] )
b = np.array( [1, 2, 3, 4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1, 2] ) 

print(a + a) 
print(a + b)
print(a + c)
print(a + d)
print(a + e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

In [26]:
A = np.full((3), 2)
B = np.full((3), 1)

# 不用迴圈:
print((A + B) * (-A / 2)) 

# 使用迴圈:
A = [2, 2, 2]
B = [1, 1, 1]

listOne = []
for i in range(len(A)):
    listOne.append(A[i] + B[i])

listTwo = []
for i in A:
    listTwo.append(i / -2)
    
results = []
for i in range(len(A)):
    results.append(listOne[i] * listTwo[i])
print(results)
        
    

[-3. -3. -3.]
[-3.0, -3.0, -3.0]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

In [32]:
a = np.ones([1, 6])
b = np.ones([6, 1])

print("內積:\n", a * b)
print("外積:\n", a @ b)

內積:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
外積:
 [[6.]]
