In [4]:
# 相同大小的陣列運算
import numpy as np

a = np.array([ 10, 20, 30, 40])
b = np.arange(4)

print(a + b)
print(a * b)

[10 21 32 43]
[  0  20  60 120]


In [5]:
# 常數與陣列運算
a = np.array([ 20, 30, 40, 50])

print(a - 10)
print(a / 10)

[10 20 30 40]
[2. 3. 4. 5.]


In [6]:
# 不同大小的陣列運算
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([1, 1])

print(data + ones_row)

[[2 3]
 [4 5]
 [6 7]]


In [8]:
# 陣列運算與容器運算的差異
# numpy的陣列運算
a = np.array([20, 30, 40, 50])
print(a + 1)

# python的list運算
a = [20, 30, 40, 50]
b = []

for item in a:
    b.append(item + 1)
print(b)


[21 31 41 51]
[21, 31, 41, 51]


In [12]:
# 用於陣列的矩陣運算
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
y = np.array([[5.], [7.]])
print(y)

[[1. 2.]
 [3. 4.]]
[[5.]
 [7.]]


In [13]:
# 轉置 array
print(a.transpose())
# 轉為 逆矩陣
print(np.linalg.inv(a))
# 返回 延數組對角線之和
print(np.trace(a))
# 以矩陣形式解線性矩陣方程
print(np.linalg.solve(a, y))

[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
5.0
[[-3.]
 [ 4.]]
