# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

In [ ]:
'''
差別:
(1) np.zeros: 產生的每個元素為真實的 0
(2) np.empty: 產生的每個元素不為真實的 0, 僅是很接近0的很小的數

設計原因:
當有時只想初始化陣列、不在意內容，使用empty能更快速產生所需要的陣列
'''

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [32]:
import numpy as np

a = np.random.rand(2, 3)
a *= 100
print('未去掉小數前:\n', a)

a = np.floor(a) #取不大於該數的最大整數
print("\n去掉小數後:\n", a)

a = np.round(a) #四捨五入
a.round()


未去掉小數前:
 [[90.64798243 54.32390231 68.52767647]
 [25.2379582   1.16370638 69.3122572 ]]

去掉小數後:
 [[90. 54. 68.]
 [25.  1. 69.]]


array([[90., 54., 68.],
       [25.,  1., 69.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [119]:
m = 20
n = 40

##### 解一
a = np.random.rand(2, 3) * (n - m)
print("a:\n", a) 
b = np.floor(a)
print("b:\n", b) 
print("結果:\n", b + m)
print("===============================================")

##### 解二
a = np.random.rand(2, 3) * (n - m)
print("a:\n", a) 
b = a
print("b:\n", b) 
print("結果:\n", (a - b % 1) + m)
print("===============================================")

# 如果a陣列沒有指定, 可以直接使用 random.randint 限制範圍
arr = np.random.randint(low = m, high = n+1, size = (2, 3))
print("額外:\n", arr)

a:
 [[ 6.86055413  6.04413112 11.41760375]
 [ 2.43272084  6.82644018  3.01438826]]
b:
 [[ 6.  6. 11.]
 [ 2.  6.  3.]]
結果:
 [[26. 26. 31.]
 [22. 26. 23.]]
a:
 [[ 5.09096066 17.17252271 11.28430746]
 [10.1950747  11.58394632  5.18806383]]
b:
 [[ 5.09096066 17.17252271 11.28430746]
 [10.1950747  11.58394632  5.18806383]]
結果:
 [[25. 37. 31.]
 [30. 31. 25.]]
額外:
 [[28 28 29]
 [39 35 24]]
