In [40]:
import numpy as np

print(np.array([1, 2, 3]) )
# 指定特定型態
print(np.array([1, 2, 3], dtype = complex) )

[1 2 3]
[1.+0.j 2.+0.j 3.+0.j]


In [41]:
# 字典型態被轉成陣列會不符合期待
print(np.array({0: 123, 1:456}))
print(np.array({0: 123, 1:456}).size)

# 先轉成有序的 List 再作轉換
print(np.array(list({0: 123, 1: 456}.items())) )

{0: 123, 1: 456}
1
[[  0 123]
 [  1 456]]


In [11]:
#從固定大小的初始值開始

# 建立由 0 組成的 2x3 陣列
print(np.zeros((2, 3)) ) # 產生真正的 0 
print(np.empty((2, 3)) ) # 很小、接近0的數字

# 建立由 1 組成的 2x3 陣列
print(np.ones((2, 3)) )

# 建立由 9 組成的 2x3陣列
print(np.full((2,3), 9) )

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]]


In [21]:
# 等差序列 不包含結尾
print(np.arange(10, 30, 5) ) 

# 等差序列 起點為0 終點為2 包含3個元素 終止點<2  會回傳公差
print(np.linspace(0, 3, 3, endpoint=False, retstep=True) )

# 等比數列  初始指數  終止點的指數 元素數量 底數
print(np.logspace(1, 10, 10, base=2))

[10 15 20 25]
(array([0., 1., 2.]), 1.0)
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [28]:
# 產生固定大小的亂數(新版)
from numpy.random import default_rng
rng = default_rng()

# 常態分佈
normal = rng.standard_normal((3, 2))
print(normal)
# 隨機分佈
random = rng.random((3, 2))
print(random)
# 整數亂數
integers = rng.integers(0, 10, size=(3, 2))
print(integers)

[[-0.74105609  1.24842156]
 [-0.95160576  0.65146132]
 [ 0.68951002  1.82891069]]
[[0.13303777 0.79361488]
 [0.71569164 0.77416063]
 [0.68490507 0.63755883]]
[[6 7]
 [3 0]
 [5 4]]


In [45]:
# 產生固定大小的亂數(舊版, 在 numpy.random 下使用)

# 常態分佈
normal = np.random.randn(3, 2)
print(normal)
# 隨機分佈
random = np.random.random((3, 2))
print(random)
# 整數亂數
integers = np.random.randint(0, 10, size=(3, 2))
print(integers)

[[ 1.00353026  0.952674  ]
 [ 0.62638316 -0.09557432]
 [-0.53029862 -0.14074215]]
[[0.3746549  0.02716831]
 [0.1997845  0.57681771]
 [0.13711958 0.68130319]]
[[6 9]
 [3 3]
 [7 9]]
