In [1]:
import numpy as np

print(np)
print(np.__version__)

<module 'numpy' from '/Users/susan_yan/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.20.1


In [2]:
# 從一個陣列開始

a = np.arange(15).reshape(3, 5)
print(a) # 利用 print 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
# 陣列的常用屬性
print("使用電腦最大位元數的int: ", a.dtype)
print("每一元素所佔空間", a.itemsize, " Bytes")

使用電腦最大位元數的int:  int64
每一元素所佔空間 8  Bytes


In [10]:
# numpy 的型態判斷

print(a.dtype == "int64")
print(a.dtype is "int64")
print(a.dtype is np.int64)

True
False
False


<>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-10-009d314fc051>:4: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(a.dtype is "int64")


In [11]:
# numpy 型態的正確用法

print(a.dtype == "int64")
print(a.dtype == np.int64)
print(a.dtype is np.dtype("int64"))

True
True
True
